### PR TITLE
[IMP] stock_release_channel_shipment_advice_deliver: Allows to display pickings in confirm wizard

### PR DESCRIPTION
**Pull request by rousseldenis**
Needs : #10 

In order to let user aware of remaining pickings when delivering, display them in the delivering wizard

image

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jbaudoux

**Comment by jbaudoux** [comment]
@rousseldenis Where do we stand with this?

**Comment by lmignon** [comment]
ping @rousseldenis

**Comment by jbaudoux** [comment]
@rousseldenis The related branch has been merged, so you'll have to close this one and reopen an new one on OCA

**Comment by rousseldenis** [comment]
> @rousseldenis The related branch has been merged, so you'll have to close this one and reopen an new one on OCA

done :-)

**Pull request closed without merging**
